version: '3'

volumes:
  mongo-data:
    driver: local
    driver_opts:
        type: xfs
        device: "/xapi_data/mongo"
        o: bind
  xapi-storage:
    driver: local
    driver_opts:
        type: xfs
        device: "/xapi_data/xapi-storage"
        o: bind
  app-storage:
    driver: local
    driver_opts:
        type: ext4
        device: "/LRS/app-storage"
        o: bind
  ui-logs:
    driver: local
    driver_opts:
        type: ext4
        device: "/LRS/ui-logs"
        o: bind

services:

    mongo:
        image: mongo:4.4.18
        restart: unless-stopped
        volumes:
            - mongo-data:/data/db

    redis:
        image: redis:latest
        restart: unless-stopped

    xapi:
        image: learninglocker/xapi-service:${XAPI_SERVICE_VERSION}
        restart: unless-stopped
        environment:
            - MONGO_URL=mongodb://mongo:27017/learninglocker_v2
            - MONGO_DB=learninglocker_v2
            - REDIS_URL=redis://redis:6379/0
        depends_on:
            - mongo
            - redis
        ports:
            - "8081:8081"
        volumes:
            - xapi-storage:/usr/src/app/storage

    api:
        image: learninglocker-app:${DOCKER_TAG}
        environment:
            - DOMAIN_NAME
            - APP_SECRET
            - SMTP_HOST
            - SMTP_PORT
            - SMTP_SECURED
            - SMTP_USER
            - SMTP_PASS
        command: "node api/dist/server"
        restart: unless-stopped
        ports:
            - "8080:8080"
        depends_on:
            - mongo
            - redis
        volumes:
            - app-storage:/opt/learninglocker/storage

    ui:
        image: learninglocker-app:${DOCKER_TAG}
        environment:
            - DOMAIN_NAME
            - APP_SECRET
            - SMTP_HOST
            - SMTP_PORT
            - SMTP_SECURED
            - SMTP_USER
            - SMTP_PASS
        command: "./entrypoint-ui.sh"
        restart: unless-stopped
        depends_on:
            - mongo
            - redis
            - api
        ports:
            - "3000:3000"
        volumes:
            - app-storage:/opt/learninglocker/storage
            - ui-logs:/opt/learninglocker/logs

    worker:
        image: learninglocker-app:${DOCKER_TAG}
        environment:
            - DOMAIN_NAME
            - APP_SECRET
            - SMTP_HOST
            - SMTP_PORT
            - SMTP_SECURED
            - SMTP_USER
            - SMTP_PASS
        command: "node worker/dist/server"
        restart: unless-stopped
        depends_on:
            - mongo
            - redis
        volumes:
            - app-storage:/opt/learninglocker/storage

